/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-11-15 07:46:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CSS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Kosmo/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/BootStrapProj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1603769861190L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->\r\n");
      out.write("    <title>Form.jsp</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- 부트스트랩 -->\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->\r\n");
      out.write("    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \t<div class=\"page-header\">\r\n");
      out.write("    \t\t<h1>폼<small> 폼연습하기</small></h1>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("    \t\t<div class=\"col-md-offset-1 col-md-10\">\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t<form>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"email\">이메일 주소</label>\r\n");
      out.write("\t\t\t\t    <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"이메일을 입력하세요\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"password\">암호</label>\r\n");
      out.write("\t\t\t\t    <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"암호\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>파일 업로드</label>\r\n");
      out.write("\t\t\t\t    <input type=\"file\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t    <p class=\"help-block\">여기에 블록레벨 도움말 예제</p>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t    <label>\r\n");
      out.write("\t\t\t\t      <input type=\"checkbox\"> 아이디 저장\r\n");
      out.write("\t\t\t\t    </label>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <button type=\"submit\" class=\"btn btn-success\" >제출</button>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("    \t\t</div>    \t\t\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<!-- row -->\r\n");
      out.write("    \t<h2>인라인 폼</h2>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-offset-1 col-md-1\">\r\n");
      out.write("               <form class=\"form-inline\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                     <label>이름</label>\r\n");
      out.write("                     <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                     <label>비밀번호</label>\r\n");
      out.write("                     <input type=\"password\" class=\"form-control\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                     <label>이메일</label>\r\n");
      out.write("                     <input type=\"email\" class=\"form-control\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                     <button type=\"submit\" class=\"btn btn-default\">확인</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </form>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- 수평 폼 -->\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("         \t<div class=\"col-md-offset-1 col-md-10\">\r\n");
      out.write("         \t\t<form class=\"form-horizontal\">\r\n");
      out.write("         \t\t\t<div class=\"form-group\">\r\n");
      out.write("         \t\t\t\t<label class=\"col-sm-2 control-label\">이메일 주소</label>\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("         \t\t\t\t\t<input type=\"email\" class=\"form-control\">\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">\r\n");
      out.write("         \t\t\t\t<label class=\"col-sm-2 control-label\">암호</label>\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("         \t\t\t\t\t<input type=\"pass\" class=\"form-control\">\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">\r\n");
      out.write("         \t\t\t\t<label class=\"col-sm-2 control-label\">제목</label>\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("         \t\t\t\t\t<input type=\"title\" class=\"form-control\">\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">\r\n");
      out.write("         \t\t\t\t<label class=\"col-sm-2\">파일 업로드</label>\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("         \t\t\t\t\t<input type=\"file\"/>\r\n");
      out.write("         \t\t\t\t\t<p class=\"help-block\">이미지 파일만 업로드 하세요</p>\r\n");
      out.write("         \t\t\t\t</div>         \t\t\t\t\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">\r\n");
      out.write("         \t\t\t\t<label class=\"col-sm-2 control-label\">성별</label>\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("         \t\t\t\t\t<!-- 가로배치 -->\r\n");
      out.write("         \t\t\t\t\t \r\n");
      out.write("         \t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"radio\" name=\"a\"/>남자</label>\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"radio\" name=\"a\"/>여자</label>\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"radio\" name=\"a\" class=\"disabled\" disabled/>젠더</label>\r\n");
      out.write("         \t\t\t\t\t</div>\r\n");
      out.write("         \t\t\t\t\t\r\n");
      out.write("         \t\t\t\t\t <!--\r\n");
      out.write("         \t\t\t\t\t <div class=\"radio\">\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"radio\" />남자</label>\r\n");
      out.write("         \t\t\t\t\t</div>\r\n");
      out.write("         \t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"radio\" />여자</label>\r\n");
      out.write("         \t\t\t\t\t</div>\r\n");
      out.write("         \t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"radio\" class=\"disabled\" disabled/>젠더</label>\r\n");
      out.write("         \t\t\t\t\t</div>\r\n");
      out.write("         \t\t\t\t\t -->\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">\r\n");
      out.write("         \t\t\t\t<label class=\"col-sm-2 control-label\">관심사항</label>\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("         \t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"checkbox\" />정치</label>\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"checkbox\" />경제</label>\r\n");
      out.write("         \t\t\t\t\t\t<label><input type=\"checkbox\" />연예</label>\r\n");
      out.write("         \t\t\t\t\t</div>\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">\r\n");
      out.write("         \t\t\t\t<label class=\"col-sm-2 control-label\">학력</label>\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("         \t\t\t\t\t<select class=\"form-control input-sm\">\r\n");
      out.write("         \t\t\t\t\t\t<option>학력을 선택하세요</option>\r\n");
      out.write("         \t\t\t\t\t\t<option>초등학교</option>\r\n");
      out.write("         \t\t\t\t\t\t<option>중학교</option>\r\n");
      out.write("         \t\t\t\t\t\t<option>고등학교</option>\r\n");
      out.write("         \t\t\t\t\t\t<option>대학교</option>\r\n");
      out.write("         \t\t\t\t\t</select>\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">\r\n");
      out.write("         \t\t\t\t<label class=\"col-sm-2 control-label\">자기소개</label>\r\n");
      out.write("         \t\t\t\t<!-- 중첩 컬럼 사용 -->\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("         \t\t\t\t\t<div class=\"row\">\r\n");
      out.write("         \t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("         \t\t\t\t\t\t\t<textarea rows=\"5\" class=\"form-control\"></textarea>\r\n");
      out.write("         \t\t\t\t\t\t</div>\r\n");
      out.write("         \t\t\t\t\t</div>       \t\t\t\t\t\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">         \t\t\t\t\r\n");
      out.write("         \t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("         \t\t\t\t\t<label class=\"col-sm-offset-2 col-sm-4\">아이디 저장</label>\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t\t<div class=\"form-group\">         \t\t\t\t\r\n");
      out.write("         \t\t\t\t<div class=\"col-sm-offset-2 col-sm-4\">\r\n");
      out.write("         \t\t\t\t\t<button class=\"btn btn-primary\">확인</button>\r\n");
      out.write("         \t\t\t\t</div>\r\n");
      out.write("         \t\t\t</div>\r\n");
      out.write("         \t\t</form>\r\n");
      out.write("         \t</div>\r\n");
      out.write("         </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("    <!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->\r\n");
      out.write("    <script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /CSS/Form.jsp(15,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/bootstrap/css/bootstrap.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /CSS/Form.jsp(184,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/bootstrap/js/bootstrap.min.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
