
/* Drop Tables 

DROP TABLE KOSMO.GALLERY CASCADE CONSTRAINTS;
DROP TABLE KOSMO.MEMBER CASCADE CONSTRAINTS;

*/


/* Create Tables */

CREATE TABLE KOSMO.GALLERY
(
	NO number NOT NULL,
	ID nvarchar2(10) NOT NULL,
	ATTACHFILE nvarchar2(20) NOT NULL,
	CONTENT varchar2(2000),
	POSTDATE date DEFAULT SYSDATE,
	LIKECOUNT number,
	CONSTRAINT SYS_C0011736 PRIMARY KEY (NO)
);


CREATE TABLE KOSMO.MEMBER
(
	ID nvarchar2(10) NOT NULL,
	PWD varchar2(15) NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	ADDR varchar2(30),
	TEL nvarchar2(20) NOT NULL,
	EMAIL varchar2(30),
	REGIDATE date DEFAULT SYSDATE,
	GENDER varchar2(10 char) NOT NULL,
	AGE number NOT NULL,
	CONSTRAINT SYS_C0011732 PRIMARY KEY (ID)
);



